[package]
name = "pos-app"
version = "1.0.0"
description = "POS System - Point of Sale"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[lib]
name = "app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-os = "2.3.2"
tauri-plugin-shell = "2"
tauri-plugin-thermal-printer = "2.0.1"
